version: '3'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.16.2
    container_name: elasticsearch
    environment:
      - node.name=elasticsearch
      - discovery.seed_hosts=elasticsearch
      - cluster.initial_master_nodes=elasticsearch
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - ./elastic_data:/usr/share/elasticsearch/data
    networks:
      - abonent

  abonent-api:
    build: ./abonent-api
    container_name: abonent-api
    environment:
      ELASTICSEARCH_URL: "http://elasticsearch:9200"
    depends_on:
      - elasticsearch
    ports:
      - "7000:7000"
    networks:
      - abonent

  abonent-server:
    build: ./abonent-server
    container_name: abonent-server
    environment:
      ELASTICSEARCH_URL: "http://elasticsearch:9200"
    depends_on:
      - abonent-api
      - elasticsearch
    ports:
      - "5000:5000"
    networks:
      - abonent

networks:
  abonent:
    driver: bridge
